env:
  browser: true
  es2021: true
  webextensions: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - prettier
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules:
  react/prop-types: 0
  no-unused-vars: 0
